SELECT 
	li.PART_KEY,
	li.SUPPLIER_KEY,
	o.CUSTOMER_KEY,
	c.NATION_KEY AS CUSTOMER_NATION_KEY,
	s.NATION_KEY AS SUPPLIER_NATION_KEY,
	od.DATE_KEY AS ORDER_DATE_KEY,
	sd.DATE_KEY AS LINE_ITEM_SHIP_DATE_KEY,
	cd.DATE_KEY AS LINE_ITEM_COMMIT_DATE_KEY,
	rd.DATE_KEY as LINE_ITEM_RECEIPT_DATE_KEY,
	li.ORDER_KEY,
	o.ORDER_STATUS_TYPE,
	o.ORDER_TOTAL_PRICE,
	o.ORDER_PRIORITY_TYPE,
	o.ORDER_CLERK,
	o.ORDER_SHIPPRIORITY,
	ps.PART_AVAILABILITY_QUANTITY,
	ps.PART_SUPPLY_COST,
	li.LINE_TIME_NUMBER,
	li.LINE_ITEM_QUANTITY,
	li.LINE_ITEM_EXTENDED_PRICE,
	li.LINE_ITEM_DISCOUNT,
	li.LINE_ITEM_TAX,
	li.LINE_ITEM_RETURN_FLAG,
	li.LINE_ITEM_STATUS_TYPE,
	li.LINE_ITEM_SHIP_INSTRUCTION_TYPE,
	li.LINE_ITEM_SHIP_MODE_TYPE,
	NOW() AS INGESTION_TIMESTAMP
FROM 
	standardized.line_items li 
LEFT JOIN
	standardized.part_suppliers ps 
	ON li.PART_KEY = ps.PART_KEY 
	AND li.SUPPLIER_KEY = ps.SUPPLIER_KEY 
LEFT JOIN 
	standardized.orders o 
	ON o.ORDER_KEY = li.ORDER_KEY 
LEFT JOIN 
	standardized.customers c 
	ON o.CUSTOMER_KEY = c.CUSTOMER_KEY 
LEFT JOIN 
	standardized.suppliers s 
	ON li.SUPPLIER_KEY = s.SUPPLIER_KEY
LEFT JOIN 
	presentation.dates od 
	ON od.`DAY` = EXTRACT(DAY FROM o.ORDER_DATE)
	AND od.`MONTH` = EXTRACT(MONTH FROM o.ORDER_DATE)
	AND od.`YEAR` = EXTRACT(YEAR FROM o.ORDER_DATE)
LEFT JOIN 
	presentation.dates sd 
	ON sd.`DAY` = EXTRACT(DAY FROM li.LINE_ITEM_SHIP_DATE)
	AND sd.`MONTH` = EXTRACT(MONTH FROM li.LINE_ITEM_SHIP_DATE)
	AND sd.`YEAR` = EXTRACT(YEAR FROM li.LINE_ITEM_SHIP_DATE)
LEFT JOIN 
	presentation.dates cd 
	ON cd.`DAY` = EXTRACT(DAY FROM li.LINE_ITEM_COMMIT_DATE)
	AND cd.`MONTH` = EXTRACT(MONTH FROM li.LINE_ITEM_COMMIT_DATE)
	AND cd.`YEAR` = EXTRACT(YEAR FROM li.LINE_ITEM_COMMIT_DATE)
LEFT JOIN 
	presentation.dates rd 
	ON rd.`DAY` = EXTRACT(DAY FROM li.LINE_ITEM_RECEIPT_DATE)
	AND rd.`MONTH` = EXTRACT(MONTH FROM li.LINE_ITEM_RECEIPT_DATE)
	AND rd.`YEAR` = EXTRACT(YEAR FROM li.LINE_ITEM_RECEIPT_DATE)
WHERE 
	li.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
