SELECT
	DISTINCT 
	s.SUPPLIER_KEY,
	s.SUPPLIER_ACCOUNT_BALANCE_TOTAL ,
	n.NATION_NAME,
	NOW() AS INGESTION_TIMESTAMP
FROM 
	standardized.suppliers s
LEFT JOIN 
	standardized.nations n 
	ON s.NATION_KEY = n.NATION_KEY 
WHERE 
	s.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)