CREATE TABLE datalake.REGION (
  R_REGIONKEY INTEGER,
  R_NAME      TEXT,
  R_COMMENT   TEXT,
  INGESTION_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE datalake.NATION (
  N_NATIONKEY INTEGER,
  N_NAME      TEXT,
  N_REGIONKEY INTEGER,
  N_COMMENT   TEXT,
  INGESTION_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE datalake.PART (
  P_PARTKEY     INTEGER,
  P_NAME        TEXT,
  P_MFGR        TEXT,
  P_BRAND       TEXT,
  P_TYPE        TEXT,
  P_SIZE        INTEGER,
  P_CONTAINER   TEXT,
  P_RETAILPRICE INTEGER,
  P_COMMENT     TEXT,
  INGESTION_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE datalake.SUPPLIER (
  S_SUPPKEY   INTEGER,
  S_NAME      TEXT,
  S_ADDRESS   TEXT,
  S_NATIONKEY INTEGER,
  S_PHONE     TEXT,
  S_ACCTBAL   INTEGER,
  S_COMMENT   TEXT,
  INGESTION_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE datalake.PARTSUPP (
  PS_PARTKEY    INTEGER,
  PS_SUPPKEY    INTEGER,
  PS_AVAILQTY   INTEGER,
  PS_SUPPLYCOST INTEGER,
  PS_COMMENT    TEXT,
  INGESTION_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE datalake.CUSTOMER (
  C_CUSTKEY    INTEGER,
  C_NAME       TEXT,
  C_ADDRESS    TEXT,
  C_NATIONKEY  INTEGER,
  C_PHONE      TEXT,
  C_ACCTBAL    INTEGER,
  C_MKTSEGMENT TEXT,
  C_COMMENT    TEXT,
  INGESTION_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE datalake.ORDERS (
  O_ORDERKEY      INTEGER,
  O_CUSTKEY       INTEGER,
  O_ORDERSTATUS   TEXT,
  O_TOTALPRICE    INTEGER,
  O_ORDERDATE     DATE,
  O_ORDERPRIORITY TEXT,  
  O_CLERK         TEXT, 
  O_SHIPPRIORITY  INTEGER,
  O_COMMENT       TEXT,
  INGESTION_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE datalake.LINEITEM (
  L_ORDERKEY      INTEGER,
  L_PARTKEY       INTEGER,
  L_SUPPKEY       INTEGER,
  L_LINENUMBER    INTEGER,
  L_QUANTITY      INTEGER,
  L_EXTENDEDPRICE INTEGER,
  L_DISCOUNT      INTEGER,
  L_TAX           INTEGER,
  L_RETURNFLAG    TEXT,
  L_LINESTATUS    TEXT,
  L_SHIPDATE      DATE,
  L_COMMITDATE    DATE,
  L_RECEIPTDATE   DATE,
  L_SHIPINSTRUCT  TEXT,
  L_SHIPMODE      TEXT,
  L_COMMENT       TEXT,
  INGESTION_TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP
);
