WITH timeframed_data AS (
	SELECT
		DISTINCT 
		CAST(C_CUSTKEY AS SIGNED) AS CUSTOMER_KEY,
		C_NAME AS CUSTOMER_NAME,
		C_ADDRESS AS CUSTOMER_ADDRESS,
		CAST(C_NATIONKEY AS SIGNED) AS NATION_KEY,
		C_PHONE AS CUSTOMER_PHONE,
		C_ACCTBAL AS CUSTOMER_ACCOUNT_BALANCE_TOTAL,
		C_MKTSEGMENT AS CUSTOMER_MARKET_SEGMENT_TYPE,
		C_COMMENT AS CUSTOMER_COMMENT,
		NOW() AS INGESTION_TIMESTAMP
	FROM
		datalake.CUSTOMER c
	WHERE 
		c.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
)

SELECT 
	* 
FROM 
	timeframed_data
