WITH timeframed_data AS (
	SELECT 
        DISTINCT
        CAST(L_ORDERKEY AS SIGNED) AS ORDER_KEY, 
        CAST(L_PARTKEY AS SIGNED) AS PART_KEY, 
        CAST(L_SUPPKEY AS SIGNED) AS SUPPLIER_KEY, 
        CAST(L_LINENUMBER AS SIGNED) AS LINE_TIME_NUMBER, 
        CAST(L_QUANTITY AS SIGNED) AS LINE_ITEM_QUANTITY, 
        CAST(L_EXTENDEDPRICE AS SIGNED) AS LINE_ITEM_EXTENDED_PRICE, 
        CAST(L_DISCOUNT AS SIGNED) AS LINE_ITEM_DISCOUNT, 
        CAST(L_TAX AS SIGNED) AS LINE_ITEM_TAX, 
        L_RETURNFLAG AS LINE_ITEM_RETURN_FLAG, 
        L_LINESTATUS AS LINE_ITEM_STATUS_TYPE, 
        CAST(L_SHIPDATE AS DATE) AS LINE_ITEM_SHIP_DATE, 
        CAST(L_COMMITDATE AS DATE) AS LINE_ITEM_COMMIT_DATE, 
        CAST(L_RECEIPTDATE AS DATE) AS LINE_ITEM_RECEIPT_DATE, 
        L_SHIPINSTRUCT AS LINE_ITEM_SHIP_INSTRUCTION_TYPE, 
        L_SHIPMODE AS LINE_ITEM_SHIP_MODE_TYPE, 
        L_COMMENT AS LINE_ITEM_COMMENT,
        NOW() AS INGESTION_TIMESTAMP
    FROM 
        datalake.LINEITEM l
    WHERE 
        l.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
)

SELECT 
	* 
FROM 
	timeframed_data