WITH timeframed_data AS (
	SELECT
        DISTINCT
        CAST(O_ORDERKEY AS SIGNED) AS ORDER_KEY,
        CAST(O_CUSTKEY AS SIGNED) AS CUSTOMER_KEY,
        O_ORDERSTATUS AS ORDER_STATUS_TYPE,
        CAST(O_TOTALPRICE AS SIGNED) AS ORDER_TOTAL_PRICE,
        CAST(O_ORDERDATE AS DATE) AS ORDER_DATE,
        O_ORDERPRIORITY AS ORDER_PRIORITY_TYPE,
        O_CLERK AS ORDER_CLERK,
        O_SHIPPRIORITY AS ORDER_SHIPPRIORITY,
        O_COMMENT AS ORDER_COMMENT,
        NOW() AS INGESTION_TIMESTAMP
    FROM
        datalake.ORDERS o
    WHERE 
        o.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
)

SELECT 
	* 
FROM 
	timeframed_data
