WITH timeframed_data AS (
	SELECT
        DISTINCT
        CAST(PS_PARTKEY AS SIGNED) AS PART_KEY,
        CAST(PS_SUPPKEY AS SIGNED) AS SUPPLIER_KEY,
        CAST(PS_AVAILQTY AS SIGNED) AS PART_AVAILABILITY_QUANTITY,
        CAST(PS_SUPPLYCOST AS SIGNED) AS PART_SUPPLY_COST, 
        PS_COMMENT AS PART_SUPPLIER_COMMENT,
        NOW() AS INGESTION_TIMESTAMP
    FROM
        datalake.PARTSUPP ps
    WHERE 
        ps.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
)

SELECT 
	* 
FROM 
	timeframed_data