WITH timeframed_data AS (
	SELECT
        DISTINCT
        CAST(P_PARTKEY AS SIGNED) AS PART_KEY,
        P_NAME AS PART_NAME,
        P_MFGR AS PART_MANUFACTURE_GROUP_NAME,
        P_BRAND AS PART_BRAND_NAME,
        P_TYPE AS PART_TYPE,
        CAST(P_SIZE AS SIGNED) AS PART_SIZE_NUMBER,
        P_CONTAINER AS PART_CONTAINER_TYPE,
        P_RETAILPRICE AS PART_RETAIL_PRICE,
        P_COMMENT AS PART_COMMENT,
        NOW() AS INGESTION_TIMESTAMP
    FROM
        datalake.PART p
    WHERE 
        p.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
)

SELECT 
	* 
FROM 
	timeframed_data
