WITH timeframed_data AS (
	SELECT
		DISTINCT 
		CAST(R_REGIONKEY AS SIGNED) AS REGION_KEY,
		R_NAME AS REGION_NAME,
		R_COMMENT AS REGION_COMMENT,
		NOW() AS INGESTION_TIMESTAMP
	FROM
		datalake.REGION r
	WHERE 
		r.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
)

SELECT 
	* 
FROM 
	timeframed_data
