WITH timeframed_data AS (
	SELECT
        DISTINCT
        CAST(S_SUPPKEY AS SIGNED) AS SUPPLIER_KEY,
        S_NAME AS SUPPLIER_NAME,
        S_ADDRESS AS SUPPLIER_ADDRESS,
        CAST(S_NATIONKEY AS SIGNED) AS NATION_KEY,
        S_PHONE AS SUPPLIER_PHONE,
        S_ACCTBAL AS SUPPLIER_ACCOUNT_BALANCE_TOTAL,
        S_COMMENT AS SUPPLIER_COMMENT,
        NOW() AS INGESTION_TIMESTAMP
    FROM
        datalake.SUPPLIER s
    WHERE 
        s.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)
)

SELECT 
	* 
FROM 
	timeframed_data