SELECT 
	DISTINCT 
	n.NATION_KEY,
	n.NATION_NAME,
	r.REGION_KEY,
	r.REGION_NAME,
	NOW() AS INGESTION_TIMESTAMP
FROM 
	standardized.nations n
LEFT JOIN 
	standardized.regions r
	ON n.REGION_KEY = r.REGION_KEY 
WHERE 
	n.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)