SELECT 
	DISTINCT
	c.CUSTOMER_KEY,
	n.NATION_NAME,
	c.CUSTOMER_ACCOUNT_BALANCE_TOTAL,
	c.CUSTOMER_MARKET_SEGMENT_TYPE, 
	NOW() AS INGESTION_TIMESTAMP
FROM 
	standardized.customers c 
LEFT JOIN
	standardized.nations n 
	ON c.NATION_KEY = n.NATION_KEY 
WHERE
	c.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)