SELECT 
	DISTINCT 
	p.PART_KEY,
	p.PART_NAME,
	p.PART_SIZE_NUMBER,
	p.PART_CONTAINER_TYPE,
	p.PART_RETAIL_PRICE,
	NOW() AS INGESTION_TIMESTAMP
FROM 
	standardized.parts p
WHERE 
	p.INGESTION_TIMESTAMP >= DATE_SUB(NOW(), INTERVAL 1 HOUR)